name: Tests
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    # Skip running tests if the push is used in a pull request from the same repository.
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
